-- جدول تخزين اشتراكات التنبيهات (Push Subscriptions) لكل جهاز فعّل التنبيهات
create table push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text unique not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz default now()
);

alter table push_subscriptions enable row level security;

create policy "قراءة عامة للاشتراكات" on push_subscriptions
  for select using (true);

create policy "إضافة عامة للاشتراكات" on push_subscriptions
  for insert with check (true);

create policy "تحديث عام للاشتراكات" on push_subscriptions
  for update using (true);

create policy "حذف عام للاشتراكات" on push_subscriptions
  for delete using (true);
